### ISSUE TITLE
You are in violation of GPL v3

### ISSUE THREAD

**Issue by bernaards** [somakd/fad#6]
Hello

I am the developer and maintainer of the GPArotation package
The GPArotation package is licensed under GPL V 3.  You are in violation of of this license because you have included code snippets directly taken and modified from the original source code without disclosing its origin.
Please update your code to clarify the origin of your rotation algorithms (incl. equamax, quartimax). This can be as a note in the text or manual files. Alternatively, you may include GPArotation in the DESCRIPTION file as  required package.

We are all working for free with the same goal in mind. For this system to continue to exist It is needed for code users to disclose code origins, consistent with the GPL license. 

If you feel that I am mistaken in this assessment, please point me in the direction of the notice

Thank you for taking care of this
Coen Bernaards

**Comment by somakd** [comment]
Thanks for pointing out. The functions equamax and quartimax were redundant and not excluded by our oversight in the previous release. They are now removed from the code, as we meant to. However, GPArotation has been added as a suggested package.

**Comment by bernaards** [comment]
thank you for taking care of this, and thank you for what you do for the R community
